### ISSUE TITLE
Unable to equip Steel Shoes correctly

### ISSUE THREAD

**Issue by Foamimi** [Coliwogg/Ores-and-Metals#1]
Hey! I was trying to equip the Steel armor set, and I noticed I couldn't equip the entire set at once. I'm able to equip the shoes, however they seem to be tagged as pants because they only work in that category. Everything else seemed fine though! :)

**Comment by Coliwogg** [comment]
Thanks for bringing this to my attention! This issue should be fixed in the version 1.1.1 update.
