### ISSUE TITLE
dark animica config

### ISSUE THREAD

**Issue by Tyrius1** [Coliwogg/Ores-and-Metals#3]
[oregen.dark_animica_ore]
		#Generate Dark Animica Ore in The Nether - [true/false]
		generate_dark_animica = true
		#Maximum height for Dark Animica Ore generation - default = 255
		#Range: 0 ~ 255
		dark_animica_max_height = 255
		#Size of Dark Animica Ore veins - default = 6
		#Range: 0 ~ 100
>!		light_animica_size = 6
		#Number of Dark Animica Ore veins generated in a chunk - default = 16
		#Range: 0 ~ 100
>!		dark_animica_size = 16
		#Minimum height for Dark Animica Ore generation - default = 20
		#Range: 0 ~ 255
		dark_animica_min_height = 255

couple issues here

**Comment by Coliwogg** [comment]
This issue should be fixed in the new Ores and Metals-1.15.2-1.2.0.1 update.
Thanks for letting me know!
